# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net 

name: DeveloperTools

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore DeveloperTools

    - name: Build
      run: dotnet build DeveloperTools --no-restore

  test:
    - name: Test
      run:  dotnet test DeveloperTools/DeveloperTools.Test/DeveloperTools.Test.csproj --no-build --verbosity normal

    - name: Install Playwright
      run: |
        dotnet tool install --global Microsoft.Playwright.CLI
        dotnet build DeveloperTools/DeveloperTools.UI.Test/DeveloperTools.UI.Test.csproj
        pwsh DeveloperTools/DeveloperTools.UI.Test/bin/Debug/net9.0/playwright.ps1 install --with-deps

    - name: UI Test
      run:  dotnet test DeveloperTools/DeveloperTools.UI.Test/DeveloperTools.UI.Test.csproj --no-build --verbosity normal